name: Build and Create Release

on:
  push:
    tags:
      - 'v*.*.*'    # trigger on semver-style tags like v1.2.3

jobs:
  build-and-release:
    runs-on: windows-latest
    env:
      RELEASE_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet client
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        shell: pwsh
        run: |
          if (Test-Path 'BPSR_ACT_Plugin.sln') {
            nuget restore 'BPSR_ACT_Plugin.sln'
          } else {
            nuget restore 'BPSR_ACT_Plugin\BPSR_ACT_Plugin.csproj'
          }

      - name: Build (Release)
        run: msbuild 'BPSR_ACT_Plugin\BPSR_ACT_Plugin.csproj' /p:Configuration=Release /m

      - name: Package build output
        shell: pwsh
        run: |
          $out = 'BPSR_ACT_Plugin\bin\Release\net48'
          if (-not (Test-Path $out)) { $out = 'BPSR_ACT_Plugin\bin\Release' }
          New-Item -ItemType Directory -Path artifacts -Force | Out-Null
          if (Test-Path $out) {
            $zip = "artifacts\BPSR_ACT_Plugin-$env:RELEASE_TAG.zip"
            Get-ChildItem -Path $out -Recurse | Compress-Archive -DestinationPath $zip -Force
            Write-Output "Packaged $zip"
          } else {
            Write-Error "Build output folder not found: $out"
            exit 1
          }

      - name: Create GitHub Release and upload artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          files: artifacts/*.zip